export { default as Boids } from "./boids.js";
export { default as Sponge } from "./sponge.js";
export { default as TSP } from "./salesman.js";
export { default as FitnessLandscape } from "./fitness-landscape.js";
export { default as SierpinskiTriangle } from "./sierpinski-triangle.js";
export { default as StrangeAttractor } from "./strange-attractors.js";
export { Sakura as Sakura } from "./turtle.js";
export { default as Wolfram } from "./wolfram.js";
export { default as Ground } from "./ground.js";
